version: "3"
services:
  app:
    build: .
    tty: true
    ports:
      - '50051:50051'
    command: go run payment-service/server/server.go
    volumes:
      - .:/go/src/app
    env_file:
      - secrets.env
  postgres:
    image: postgres:11.6-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: {}
